### ISSUE TITLE
Complete a Single Sign On (SSO) solution

### ISSUE THREAD

**Issue by 2041876935** [calpirateparty/GLAP#12]
This should be priority #1

**Comment by sptankard** [comment]
This issue depends on #16.

**Comment by 2041876935** [comment]
It would be nice if this issue could include some sort of identity profile management system. No idea what those are called. But basically I think all of our members should have a uniform profile page, something that could easily be linked to at a moments notice. maybe something like members.calpirateparty.org/* whereby * = username. Each member profile could include links to all relevant profiles and forms of contact etc etc

**Comment by sptankard** [comment]
Hmm. There's bound to be functionality of that sort in [CiviCRM](https://civicrm.org/), but that's a large package with a lot of overhead that we might not want. (Or we might, eventually.)

I think we need to brainstorm what all other functionality we are going to want. Tracking members and volunteers, donors, affiliates, ...

I think we should probably implement SSO first just to get basic functionality in place.

**Comment by sptankard** [comment]
Closing and moving to calpirateparty/CAPP#16.
