### ISSUE TITLE
Create a Welcome page for Rocket.Chat

### ISSUE THREAD

**Issue by ghost** [calpirateparty/GLAP#14]
...complete with a map of membership using js umap

**Comment by 2041876935** [comment]
How can we use this https://github.com/umap-project/umap to replace this https://www.google.com/maps/d/viewer?mid=1Pl8z14jvIidMY1OqpHvMnnwvVd8&ll=35.906152901383784%2C-120.1387378&z=6

**Comment by AaronBurrSir** [comment]
Yes please. This is direly needed. I would _actually_ suggest we make this a high priority issue.

**Comment by sptankard** [comment]
Tagging D-IT for the uMap integration and D-COMM for the text/verbiage for the RocketChat welcome page.

**Comment by sptankard** [comment]
Perhaps we should split this into two issues? I'm also wondering about what we are actually looking to set up here. I'm not convinced the RocketChat welcome page is the best main-landing-page, maybe it's better for that to be on the wiki? More/richer content? Also I'm seeing that we want:

- A world-readable (read-only) viewable copy of the RocketChat chat streams
- A page where people can sign up for RocketChat and participate in the conversation
- a page linking to the map, the chat, and our various others infrastructure components, and explaining what is for what and also background on how CAPP is organized etc.

**Comment by sptankard** [comment]
https://gis.stackexchange.com/questions/92120/how-to-make-a-private-osm-save-personal-information-to-a-map-using-openlayer-o

**Comment by AaronBurrSir** [comment]
I'm mainly looking for "A page where people can sign up for RocketChat and participate in the conversation".

For example, I want to make an ad set on Facebook that sends people to a page with something like, "Welcome to the landing page of the California Pirate Party! Use this link to register a new account with Rocket.Chat to join the conversation. If you want to see what we're talking about before joining, please follow this link (link to read only chat).
If you want to learn more about the party before registering, please go here (links to the CAPP website and/or Wiki)

**Comment by sptankard** [comment]
Why don't we draft the text etc. of what we want the landing page to be on this page: https://wiki.calpirateparty.org/Main_Page
...then we can move it into place/wherever we want later.

**Comment by sptankard** [comment]
This is the current/competing page and possible the canonical URL that we may want to use: https://www.calpirateparty.org/get-involved/

I'm thinking we should use the WP-wiki plugin to set the content of that page to update from a page on the wiki, for easier editing.

**Comment by sptankard** [comment]
@AaronBurrSir https://wiki.calpirateparty.org/Main_Page#General_Information

**Comment by sptankard** [comment]
Closing, this has now been done!
