### ISSUE TITLE
Survey and settle on a liquid-democracy software platform

### ISSUE THREAD

**Issue by sptankard** [calpirateparty/GLAP#15]
Loomio
Adhocracy - currently trying, some downsides (unmaintained; lacking features like filtering by voted already/not-yet)
Consider.it - proprietary

...others?

**Comment by sptankard** [comment]
https://www.loomio.org/about

**Comment by AaronBurrSir** [comment]
I dont like Adhocracy so far. The UI is not very intuitive. I didn't really like Consider.it either. I'll take a look at loomio.

**Comment by lolkje** [comment]
Laura here. The source code for Adhocracy is available for download under a Creative Commons Adapt-Attribute-ShareAlike license. I'm interested in seeing if we can get our own Adhocracy server set up, and do our own improvements to the UI. (Adding flags for issues we've voted on, showing the rate of participation, the rate of support, etc). The server setup is not my thing, but I could definitely dive into the source code. If we adapt it so it's really useful for us, it could be a model for other Pirate groups to use.

**Comment by sptankard** [comment]
I'm very supportive of contributing back to whichever project we settle on, but I think the key thing is to first survey what's out there and find the best one,so we expend minimal effort. This includes features and also the existence of an active developer community.

From what i'm seeing, it appears that Adhocracy is something of an abandoned project and that the liquid democracy world has progressed since then. So I think Adhocracy would be a very sub-optimal starting point for CAPP.

I think the project being libre/FOSS is something of a prerequisite. (Unfortunately consider.it is closed source/proprietary, but if they decide to open source it then it would be worth another look.)

I've heard good things about Loomio, so i think we should check it out next. But we should probably check out a few others too…

http://metagovernment.org/wiki/active_projects

https://github.com/coorasse/Airesis

Some suggested criteria:

- free-libre-open-source
- under active development, maintained
- friendly developer community
- decent security
- featureful
- just works
- approval voting and ranked choice voting


On April 24, 2017 8:52:00 PM PDT, AaronBurrSir <notifications@github.com> wrote:
>I dont like Adhocracy so far. The UI is not very intuitive. I didn't
>really like Consider.it either. I'll take a look at loomio. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/calpirateparty/GLAP/issues/15#issuecomment-296892680

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by davipirata** [comment]
moved
