### ISSUE TITLE
Implement a CAPP email solution

### ISSUE THREAD

**Issue by sptankard** [calpirateparty/GLAP#16]
I have just forked three projects, which I think should inform our setup, into the calpirateparty account:

https://github.com/calpirateparty/modoboa
https://github.com/calpirateparty/mailinabox
https://github.com/calpirateparty/sovereign

**Comment by sptankard** [comment]
This document is of particular interest. Good checklist for our email setup (whether or not we base it on mailinabox): https://github.com/mail-in-a-box/mailinabox/blob/master/security.md

**Comment by AaronBurrSir** [comment]
We should bump priority on this to be higher. I would suggest that we integrate a solution _now_ to have password reset/retrieval/support for rocket chat and then setup a more long term solution after that (if we dont just like the initial solution we have setup.)

**Comment by sptankard** [comment]
I've been looking into some of the details of the three projects I listed, to determine which one to go with. At this point, it looks like Sovereign is the best bet.

Modoboa doesn't have much documented in the way of security, and I also noticed they seem to roll their own webmail client (rather than using e.g. Roundcube), which doesn't fill me with confidence. 

Mailinabox is generally a bit rigid and would probably need excessive tweaking for our use case.

I'll try to point Sovereign at a VPS sometime in the next few days and test it out.

**Comment by sptankard** [comment]
Note: One thing which Modoboa *does* provide is LDAP/SSO integration. 
https://modoboa.readthedocs.io/en/latest/configuration.html#external-authentication

I may try to lift some of the Modoboa SSO config automation code and integrate it into the Sovereign solution; but this can be a second step after getting basic email set up for password reset/retrieval/support for Rocket.

**Comment by davipirata** [comment]
I am going to send this issue to CAPP as part of the #22 . Ahoy!
