### ISSUE TITLE
Implement a comprehensive backup solution

### ISSUE THREAD

**Issue by sptankard** [calpirateparty/GLAP#17]
Automated! Should include:

- all var-www content on server
- server config
- select crypto-keys
- third-party accounts e.g. FB, Twitter datadump etc.

I'd like to suggest we implement both a push solution as well as a pull solution, storing backups on trusted personal endpoint devices (probably the security team or the IT team). Pull solution can pull from the central pushed-to repository.

**Comment by sptankard** [comment]
Marking as Priority for at least implementing a basic/rudimentary backup solution.

**Comment by davipirata** [comment]
Moved
