### ISSUE TITLE
Draft a comprehensive infosec policy document

### ISSUE THREAD

**Issue by sptankard** [calpirateparty/GLAP#18]
Draft a comprehensive organization-internal infosec policy document.

**Comment by sptankard** [comment]
https://chat.calpirateparty.org/channel/infosec_policy
https://wiki.calpirateparty.org/Infosec_policy
https://wiki.calpirateparty.org/CAPP_Organizational_Structure

**Comment by 2041876935** [comment]
I think "opsec_policy" should just be renamed "Security" for simplicity

**Comment by 2041876935** [comment]
I've Moved this Issue to CAPP

[https://github.com/calpirateparty/CAPP/issues/9]
