### ISSUE TITLE
Merge wiki pages [[Greater_Los_Angeles_Pirate_Party]] and [[GLAP/Welcome_Page]]

### ISSUE THREAD

**Issue by sptankard** [calpirateparty/GLAP#25]
We should merge these, or clearly define what each one covers:

https://wiki.calpirateparty.org/Greater_Los_Angeles_Pirate_Party
https://wiki.calpirateparty.org/GLAP/Welcome_Page

**Comment by 2041876935** [comment]
I think it is too large to be inline. Probably needs its own sub-Page. I've updated https://wiki.calpirateparty.org/Greater_Los_Angeles_Pirate_Party if that works for you, CLOSE this Issue

**Comment by sptankard** [comment]
Yep seems pretty good, let's close.
