### ISSUE TITLE
Make a landing page at glap.calpirateparty.org

### ISSUE THREAD

**Issue by sptankard** [calpirateparty/GLAP#29]
I think we should copy PP Australia: https://pirateparty.org.au/

**Comment by sptankard** [comment]
Drafting text: https://pad.calpirateparty.org/p/landing-page-BTFkCAV9jU

**Comment by sptankard** [comment]
Cf. also calpirateparty/CAPP#23

**Comment by davipirata** [comment]
Ok... on the technical issue I am going to ramp this up to L-4... we did:
* wordpress is now multisite
* glap.calpirateparty.org points to the right place
* glap has its own site under wordpress instance.

ToDo (fixes):
* There is no https
* Wordpress not login in with username, only e-mail addresses.
