### ISSUE TITLE
Manual for newcomers 

### ISSUE THREAD

**Issue by davipirata** [calpirateparty/GLAP#4]
We should have a friendly page explaining how we work

**Comment by 2041876935** [comment]
We can start crowd-sourcing the welcome page HERE: https://wiki.calpirateparty.org/Welcome_Page

**Comment by 2041876935** [comment]
better yet, it can birth out of this: https://wiki.calpirateparty.org/CAPP_Organizational_Structure

**Comment by sptankard** [comment]
cf. also https://starters.servo.org/

Should be some good stuff in the tagging system that we can pirate and adapt to organizational tasks (as opposed to programming tasks).

**Comment by davipirata** [comment]
Ok... I am closing this issue since I think the idea was to create the page and it is there now:
[GLAP - Welcome Page](https://wiki.calpirateparty.org/Welcome_Page)

Now... I will open another issue to ask you guys to edit/proof read it.
