### ISSUE TITLE
Create a step-by-step guide for Registering as a Pirate

### ISSUE THREAD

**Issue by 2041876935** [calpirateparty/GLAP#7]
using the secretary of state website create a guide -complete with screenshots- to registering as a pirate in california

We can use https://wiki.calpirateparty.org/Register_to_vote

**Comment by AaronBurrSir** [comment]
I haven't re-registered as a Pirate yet for California. I'll do that this week/weekend and provide screenshots of the entire process.

**Comment by 2041876935** [comment]
Cool! I will leave this one up to you. I'll assign you as soon as you join the group.

/Moving to CAPP

**Comment by davipirata** [comment]
I am going to close this one here as it is more pertinent to CAPP
