### ISSUE TITLE
Condense #Channels on Rocket.Chat

### ISSUE THREAD

**Issue by ghost** [calpirateparty/GLAP#9]
too many channels

some are redundant

lets reduce the number of channels

**Comment by 2041876935** [comment]
terrible formatting issues, but start here maybe: https://pad.calpirateparty.org/p/ChannelList1

**Comment by AaronBurrSir** [comment]
I've added my thoughts on the channel list. I'll say it once more as I feel strongly about it, I want one channel specifically devoted to real time online meetings. this can replace the meeting minutes and meetingagendas channels we have and move chat discussion from General to its own dedicated channel. That's literally my only request : )

**Comment by 2041876935** [comment]
COMMUNICATIONS
ELECTIONS
GENERAL
IT
LEGAL

**Comment by AaronBurrSir** [comment]
I mentioned on the Etherpad, but I would amend your suggestion with:

COMMUNICATIONS
ELECTIONS
GENERAL
IT
LEGAL
PARLAY - For the bi-weekly/monthly CAPP online meetings. No other purpose.

**Comment by lolkje** [comment]
The meeting agendas channel isn't being really used. It could easily be repurposed into a meeting chat channel. :) Several of the channels could be cleaned out once we get a liquid democracy platform up and running, and resolve the etherpad/wiki debate. Things are currently being discussed on channels for lack of a better place to discuss them.

**Comment by DavidinSanPedro** [comment]
Internet and social media are designed to facilitate engagement. But, ultimately it needs to be local action and connection and commonality that guides a movement to take substantial and effective action. For now, I think we need a more robust live presence. Not so much at the neglect of the current documentation drive, but to move into real life action.

**Comment by sptankard** [comment]
@AaronBurrSir can you describe why you want a dedicated #parlay channel rather than using #general? I think I may already agree with you but just wondering what your thought process was.

**Comment by sptankard** [comment]
@DavidinSanPedro I agree.

@lolkje I think the etherpad/wiki debate has been mostly resolved, no? We're actively using both. I think the people suggesting we drop the wiki (incl. myself) started using the wiki and just changed our minds.

**Comment by sptankard** [comment]
Closing, this has now been done!
